name: my_app
description: A new Flutter web app

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.5
  syncfusion_flutter_pdf: ^24.2.6

  http: ^0.13.6
  google_fonts: ^4.0.4
  page_transition: ^2.1.0
  font_awesome_flutter: ^10.7.0
  file_picker: ^6.1.1
  url_launcher: ^6.1.10
  lucide_icons: ^0.257.0
  fl_chart: ^0.63.0
  pdf_text: ^0.5.0
 


  # Other common packages you might need
  cupertino_icons: ^1.0.2


flutter:
  uses-material-design: true
