name: my_app
description: A new Flutter web app

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.5
  http: ^1.3.0


  # Other common packages you might need
  cupertino_icons: ^1.0.2
