// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlQ7vQTHYLhIsm_vxi4Ctr0Py-uS8WpXc',
    appId: '1:581341170423:web:ec0cad1c25ffba14ec61f2',
    messagingSenderId: '581341170423',
    projectId: 'careerpath-50593',
    authDomain: 'careerpath-50593.firebaseapp.com',
    storageBucket: 'careerpath-50593.firebasestorage.app',
    measurementId: 'G-RS54YJ1PWT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhqEDnoxiRgIK08DeoV2P02qho50VWtYs',
    appId: '1:581341170423:android:b8b4b79efd25fd18ec61f2',
    messagingSenderId: '581341170423',
    projectId: 'careerpath-50593',
    storageBucket: 'careerpath-50593.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDneo5b-3uClAe2K1ugzV3ry-ofHuXLj2c',
    appId: '1:581341170423:ios:8424d757c6376668ec61f2',
    messagingSenderId: '581341170423',
    projectId: 'careerpath-50593',
    storageBucket: 'careerpath-50593.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDneo5b-3uClAe2K1ugzV3ry-ofHuXLj2c',
    appId: '1:581341170423:ios:8424d757c6376668ec61f2',
    messagingSenderId: '581341170423',
    projectId: 'careerpath-50593',
    storageBucket: 'careerpath-50593.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDlQ7vQTHYLhIsm_vxi4Ctr0Py-uS8WpXc',
    appId: '1:581341170423:web:45b21077e9f551c4ec61f2',
    messagingSenderId: '581341170423',
    projectId: 'careerpath-50593',
    authDomain: 'careerpath-50593.firebaseapp.com',
    storageBucket: 'careerpath-50593.firebasestorage.app',
    measurementId: 'G-QSFC0J4NRF',
  );
}
