import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart'; // This is auto-generated by `flutterfire configure`
import 'package:google_fonts/google_fonts.dart';
import 'package:my_app/screens/gpt_screen.dart';
import 'package:my_app/screens/landing_screen.dart';
import 'package:my_app/screens/profile_screen.dart';
import 'package:my_app/screens/register_screen.dart';
import 'screens/login_screen.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'CareerGPT',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        textTheme: GoogleFonts.notoSansTextTheme(),
        useMaterial3: true,
        colorSchemeSeed: Colors.indigo,
      ),
      initialRoute: '/login', // 👈 Start with login screen
      routes: {
        '/land': (context) => LandingScreen(),
        '/login': (context) => LoginScreen(),
        '/signup': (context) => RegisterScreen(),
        '/chatGPT': (context) => ChatGPTScreen(),
        '/dashboard': (context) => ProfileScreen(),
        // Add more as needed
      },
    );
  }
}
